#!/usr/bin/env bash

# No, I don't want Node on my machine -- this is my workaround.
# Yes, I'm scared of Javascript and everything it touches.
# I only use it here because GitHub forces me to.
# There you have it. Let's move on.

set -eu

project_name="$(basename ${PWD})"
container_name="${project_name}-node-box"

container_exists() {
    docker ps --all --format 'table {{.Names}}' | grep -qc "${1}"
}

if ! container_exists "${container_name}"; then
    docker run \
        --detach --rm \
        --name "${container_name}" \
        -v "$PWD":/usr/src/app \
        -w /usr/src/app \
        node:12-slim \
        tail -f /dev/null # block
    echo "Container ${container_name} started -- don't forget to stop it later!"

    docker exec -it \
        -w /usr/src/app \
        "${container_name}" \
        npm run prepare
fi

docker exec -it \
    -w /usr/src/app \
    "${container_name}" \
    "${@}"
